server:
  port: 8081
  session-timeout: 30
  context-path: /
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.230:8761/eureka/

spring:
  primaryDataSource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 300
  secondaryDatasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true
    username: root
    password: root
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 300
  jpa:
    multitenant.default-id: test
    generate-ddl: true 
    show-sql: true
    hibernate.current_session_context_class: jta
    databasePlatform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      net.sf.ehcache.configurationResourceName: conf/ehcache-hibernate-local.xml
  redis:
    host: localhost
    port: 6379
    password: 
    database: 1
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: 0
    #sentinel.master: # name of redis server
    #sentinel.nodes: # comma-separated list of host:port pairs   
          
      
multitenancy:
  hibernate.multiTenancy: SCHEMA
  hibernate.tenant_identifier_resolver: com.ido85.frame.multitenant.TenantIdResolver
  hibernate.multi_tenant_connection_provider: com.ido85.frame.multitenant.SchemaBasedMultiTenantConnectionProvider
    
shiro:
  encrypt.salt-disabled: false
  encrypt.hash-interations: 2
  encrypt.remember-me.cipher-key: 04feRNI3snfin3VDAF3DA==
  session.active-session-cache-name: activeSessionsCache
  
threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 300
  
# business log config
businesslog.enable: true

logging:
  config: classpath:logback-prod.xml
  path: ./logs